DROP TABLE IF EXISTS Repid;
DROP TABLE IF EXISTS Disease;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS DiseaseRegion;
DROP TABLE IF EXISTS RepidRegion;


DROP TABLE IF EXISTS Region;
CREATE TABLE Region (
    RegionID INTEGER PRIMARY KEY AUTOINCREMENT,
    Latitude REAL,
    Longitude REAL,
    RepID INTEGER NOT NULL,
    Frequency INTEGER,
    UNIQUE(Latitude, Longitude, RepID),
    FOREIGN KEY (RepID) REFERENCES Repid(RepID)
);

CREATE TABLE Repid (
    RepID INTEGER PRIMARY KEY AUTOINCREMENT,
    RepidName VARCHAR(100), 
    Inheritance TEXT,
    RepeatLocation TEXT,
    NormalRange TEXT,
    IntermediateRange TEXT,
	FullMutationRange TEXT,
    Link TEXT,
    Unique(RepidName)
);

DROP TABLE IF EXISTS Disease;
CREATE TABLE Disease (
    DiseaseID INTEGER PRIMARY KEY AUTOINCREMENT,
    DiseaseName TEXT,
    RepID INTEGER NOT NULL,
    UNIQUE(DiseaseName, RepID),
    FOREIGN KEY (RepID) REFERENCES Repid(RepID)
);
CREATE TABLE DiseaseRegion (
    DiseaseRegionID INTEGER PRIMARY KEY AUTOINCREMENT,
    DiseaseID INTEGER NOT NULL,
    RegionID INTEGER NOT NULL,
    FOREIGN KEY (DiseaseID) REFERENCES Disease(DiseaseID) ON DELETE CASCADE,
    FOREIGN KEY (RegionID) REFERENCES Region(RegionID) ON DELETE CASCADE
);

CREATE TABLE RepidRegion (
    RepidRegionID INTEGER PRIMARY KEY AUTOINCREMENT,
    RepID INTEGER NOT NULL,
    RegionID INTEGER NOT NULL,
    FOREIGN KEY (RepID) REFERENCES Repid(RepID) ON DELETE CASCADE,
    FOREIGN KEY (RegionID) REFERENCES Region(RegionID) ON DELETE CASCADE
);




